import dash_bootstrap_components as dbc
import dash_core_components as dcc
from dash_html_components import *
import dash_html_components as html
from utils import anchor_projects

def layout():
    if(anchor_projects):
        return html.Div(id="anchor", children=
               dbc.Col(
                   width=12,
                   className='text-justify md-2', children=[
                    H2("Anchored combination data",className='text-center'),
                    H3("Cell lines"),
                    P(["Cell lines were acquired from commercial cell banks. All cells were grown in RPMI (supplemented with 10% FBS, 1% Penicillin/Streptomycin, 1% Glucose, 1 mM Sodium Pyruvate) or DMEM/F12 media (supplemented with 10% FBS, 1% Penicillin/Streptomycin) at 37°C in a humidified atmosphere at 5% CO2. To prevent cross-contamination or misidentification, all lines were profiled using a panel of 94 SNPs (Fluidigm, 96.96 Dynamic Array IFC). Short tandem repeat (STR) analysis was also performed, and cell line profiles were matched to those generated by the cell line repository. Further information on the cell lines used in this study, including molecular profiling datasets can be found on ",
                       A("cellmodelpassports.sanger.ac.uk .", href="https://cellmodelpassports.sanger.ac.uk/")]),

                    H3("Compounds"),
                    P(["Compounds were sourced from commercial vendors. ",
                       "DMSO-solubilised compounds were stored at room temperature in low humidity (<12%), low oxygen (<2.5%) environment using storage pods (Roylan Developments). Water-solubilised compounds were maintained at 4°C. ",
                       "Anchor and library concentrations were drug- and tissue-specific and determined from a small pilot screen, testing the drugs in 9-13 cell lines per tissue (breast: 13, colon: 9, pancreas: 12) and settling for concentrations giving moderate activity (60-90% viability) in the majority of models. ",
                       "Screening concentrations typically did not exceed 10 μM . Anchor drugs were screened at two fixed concentrations with a 2, 4, or 10-fold difference between them. ",
                       "Library drugs were screened at seven concentrations spanning a 1,000-fold range with a discontinuous log2 design of two 4-fold steps followed by four 2-fold dilution steps starting at the highest used concentration (Figure 1). ",
                       "Alternative to μM concentration ranges, drug concentrations and IC50s can be visualised on a normalised log2 scale, with 9 equalling the highest screened concentration. On each plate, all single agents were screened at five and four technical replicates for anchors and libraries, respectively."
                       ]),

                    #figure
                       Center([Img(src="assets/Fig1.png")]),
                       Br(),
                       Br(),
                       H4(Em("Figure 1: layout of the anchored drug combination screening design"),className='text-center'),

                       Br(),
                       Br(),
                    H3("Screening"),
                    P(["Cells were transferred into 1536-well plates in 7.5 μL of their respective growth medium using XRD384 (FluidX) dispensers."
                       "The seeding density was optimised to ensure that each cell line was in the exponential growth phase at the end of the assay.",
                       "For this, six seeding densities with a two-fold dilution step were each dispensed into 224 wells of a single 1536-well assay plate (XRD384 (FluidX) dispenser) and cells were incubated for 96 hours. Cell number was quantified using CellTiter-Glo 2.0 (Promega).",
                       "The maximum density tested varied based on cell type, typically 5,000 cells/well for suspension cells and 1,250 cells/well for adherent cells.",

                       ]),
                    P(["Assay plates were incubated at 37 °C in a humidified atmosphere at 5% CO2 for 24 hours then dosed with the test compounds using an Echo555 (Labcyte), final DMSO concentration was typically 0.2%.",
                        "Following dosing, plates were incubated, and the drug treatment duration was 72 hours. To measure cell viability, 2.5 μL of CellTiterGlo 2.0 (Promega) was added to each well and incubated at room temperature for 10 minutes; quantification of luminescence was performed using a Paradigm (Molecular Devices) plate reader.",

                    ]),

                    H3("Assay plate quality control"),
                    P(["All screening plates contained negative control wells (untreated wells, n = 6; DMSO-treated wells, n = 126) and positive control wells (blanks, i.e. medium only wells, n = 28; Staurosporin treated wells, n = 20; and MG-132 treated wells, n = 20) distributed across the plate. We used these positive and negative control wells to test whether the plates meet defined quality control criteria.",
                       "For instance, a maximum threshold of 0.18 was applied to the coefficient of variation (CV) of the DMSO-treated negative controls (CV = σN/μN, with σN the standard deviation of negative controls and μN the mean of the negative controls).",
                        "Using the DMSO-treated negative controls and all three positive controls, we determined Z-factors (aka Z’; Z-factor = 1 - 3*(σP + σN) / (|μP - μN|), with σN and σP the standard deviation of the negative and positive controls, and μN and μP the mean of the negative and positive controls, respectively).",
                        "The Z-factors were required to exceed a minimum threshold of 0.3 for individual plates and a mean of 0.4 across all plates within a screening set. Plates that did not meet these requirements were excluded from the study. ",
                       ]),

                    H3("Curve fitting"),
                    P(["For each plate, the raw fluorescent intensity values were normalised to a relative viability scale (ranging from 0 to 1) using the positive (PC) and negative control (NC) values (viability = (Treated cells - PC)/(NC - PC)).",
                        "Anchor viability was determined from the mean across the five replicate wells screened on each plate. All library drug dose response curves were fitted as a 2-parameter sigmoid function (Vis et al. 2016).",
                        "The dose response curves for the combinations were fitted in a similar way, but with two notable differences: 1) the cell line parameters were obtained from the library drug fits; and 2) the maximum viability was capped at the anchor viability (rather than from 0 to 1).",
                        "To assess the quality of the fits, we computed the root mean square error (RMSE). Library and combination responses with RMSE > 0.2 were excluded from the study.",
                       "Using the fitted models, we determined the IC50 and Emax (viability at highest used concentration) parameters for each dose-response curve. These are called library_IC50 and library_Emax or combi_IC50 and combi_Emax for library and combination responses, respectively (Figure 2).",
                    ]),
                    # figure
                       H4("Curve fitting",className='text-center'),
                       Center([Img(src="assets/Fig2_curve_fitting.png")]),
                       Br(),
                       Br(),
                       H4(Em("Figure 2: schematic representation of curve fitting with the anchored combination format"),className='text-center'),

                   Br(),
                   Br(),
                    H3("Detecting synergy"),
                    P(["To detect synergy we compared observed combination responses to expected combination responses.",
                        "For the latter, we used Bliss independence(Bliss 1939) of the response to the anchor and the library drug alone.",
                       "Conceptually, every point on the Bliss dose response curve is defined as the product between the anchor viability and the corresponding point on the library dose response curve.",
                       "Shifts in potency (ΔIC50) and in efficacy (ΔEmax) were calculated as the difference between the observed combination response and Bliss (ΔIC50 = Bliss_IC50 - combi_IC50, and ΔEmax = Bliss_Emax - combi_Emax) (Figure 3).",
                       "A given measurement was synergistic if the combo_IC50 was ≤ 10 (2-fold higher than the highest screened library concentration) and either the ΔIC50 or the ΔEmax was above a specific threshold: ΔIC50 ≥ 3 (23= 8-fold shift in IC50) or the ΔEmax ≥ 0.2 (20% shift in viability).",
                       "Replicate measurements of ‘anchor-library-cell line’ tuples were summarised as synergistic if half or more of the replicate measurements showed synergy.",
                       "To summarise both anchor concentrations, we considered a ‘combination-cell line’ pair as synergistic if synergy was observed at either anchor concentration. ",
                       ]),
                    # figure
                       H4("Quantifying synergy",className='text-center'),
                       Center([Img(src="assets/Fig3_quantifying_synergy.png")]),
                    Br(),
                    Br(),
                       H4(Em("Figure 3: schematic representation of synergy quantification with the anchored combination format"),className='text-center'),
                   Br(),
                   Br(),

                    H3("Reproducibility"),
                    P(["To assess the reproducibility within a screen, we have generated 2-18 biological replicates for 4-5 cell lines per tissue (breast: 5 (AU565, BT-474, CAL-85-1, HCC1937, MFM-223); colon: 4 (HCT-15, HT-29, SK-CO-1, SW620); pancreas: 5 (KP-1N, KP-4, MZ1-PC, PA-TU-8988T, SUIT-2)).",
                        "Single agent and combination responses were averaged across technical replicates (typically three per biological replicate) and correlated (Pearson correlation coefficient; minimum of 322 biological replicate pairs per ‘metric-tissue’ pair).",
                       ]),
                    P(["To assess the reproducibility of the screen, we rescreened a subset of combinations in each tissue (breast: 51 combos in 34 cell lines; colon: 45 combos in 37 cell lines; pancreas: 59 combos in 29 cell lines).",
                        "Drug combination responses were averaged across replicates within a screen and key metrics of single agent and combination response were correlated between the two screens (Pearson correlation coefficient).",
                        "To determine the quality of synergy calls, the original screen was considered as ground truth and numbers of true positive (TP), false positive (FP), true negative (TN) and false negative (FN) synergistic combination-cell line pairs were calculated.",
                       "These were used to calculate F-score (F-score =TP / (TP + 0.5*(FP + FN))), recall (recall = TP / (TP + FN)), and precision (precision = TP / (TP + FP)) per tissue.",
                        "To investigate the strength of effects of ΔEmax and ΔIC50 of FP and FN measurements, the distance to ΔEmax and ΔIC50 synergy thresholds was calculated for each ‘anchor concentration-library-cell line’ tuple based on combination responses averaged across replicates (n = 9,570 tuples).",
                       ]),


                    H3("References"),
                    P("Bliss, C. I. 1939. “The Toxicity of Poisons Applied Jointly 1.” The Annals of Applied Biology 26 (3): 585–615."),
                    P("Vis, Daniel J., Lorenzo Bombardelli, Howard Lightfoot, Francesco Iorio, Mathew J. Garnett, and Lodewyk Fa Wessels. 2016. “Multilevel Models Improve Precision and Speed of IC50 Estimates.” Pharmacogenomics 17 (7): 691–700.")
               ]
            ) #col
        )  # html



